language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis-server
cache: pip
notifications:
    email: false
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script:
  - sh bin/travis-run.sh
  - pycodestyle --count ./ckanext/tayside
after_success:
    - coveralls
